import { StyleSheet } from 'react-native';

import { Palette } from '@/constants/colors';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: Palette.cardBackground,
    borderRadius: 24,
    padding: 20,
    shadowColor: Palette.shadow,
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 16,
    elevation: 4,
    gap: 14,
  },
  toggle: {
    flexDirection: 'row',
    backgroundColor: Palette.toggleTrack,
    borderRadius: 999,
    padding: 4,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 999,
  },
  toggleBtnActive: {
    backgroundColor: Palette.cardBackground,
    shadowColor: Palette.shadow,
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  toggleText: {
    fontSize: 15,
    fontWeight: '600',
    color: Palette.textSubtle,
  },
  toggleTextActive: {
    color: Palette.cardBackground,
  },
  amountWrap: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  amount: {
    fontSize: 56,
    fontWeight: '700',
    color: Palette.text,
    letterSpacing: -1,
  },
  amountMuted: {
    color: Palette.amountPlaceholder,
  },
  hiddenInput: {
    position: 'absolute',
    opacity: 0,
    height: 1,
    width: 1,
  },
  titleInput: {
    fontSize: 17,
    fontWeight: '500',
    color: Palette.text,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: Palette.surface,
    borderRadius: 14,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: Palette.surface,
    borderRadius: 14,
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  rowLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: Palette.text,
  },
  rowValue: {
    fontSize: 16,
    color: Palette.text,
  },
  rowValueMuted: {
    color: Palette.iconMuted,
  },
  wheelWrap: {
    backgroundColor: Palette.cardBackground,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Palette.border,
    overflow: 'hidden',
  },
  submit: {
    backgroundColor: Palette.brand,
    paddingVertical: 16,
    borderRadius: 999,
    alignItems: 'center',
    marginTop: 4,
  },
  submitDisabled: {
    backgroundColor: Palette.submitDisabled,
  },
  submitText: {
    color: Palette.cardBackground,
    fontSize: 17,
    fontWeight: '700',
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: Palette.transparent,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: Palette.cardBackground,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 540,
    marginBottom: -500,
  },
  sheetGrabber: {
    paddingVertical: 4,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: Palette.sheetHandle,
    marginBottom: 8,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.border,
    marginBottom: 4,
  },
  sheetTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: Palette.text,
  },
  sheetCancel: {
    fontSize: 16,
    color: Palette.text,
  },
  sheetEdit: {
    fontSize: 16,
    color: Palette.brand,
    fontWeight: '600',
  },
  sheetHeaderSpacer: {
    width: 50,
  },
  sheetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    gap: 12,
  },
  categoryDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  categoryRowMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    justifyContent: 'space-between',
  },
  categoryRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  sheetRowSelect: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetRowText: {
    fontSize: 17,
    color: Palette.text,
  },
  sheetRowMuted: {
    color: Palette.iconMuted,
  },
  deleteBtn: {
    paddingHorizontal: 2,
  },
  addRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.border,
    marginTop: 4,
  },
  addInput: {
    flex: 1,
    backgroundColor: Palette.surface,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: Palette.text,
  },
  repeatBody: {
    paddingTop: 8,
    gap: 14,
  },
  repeatToggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: Palette.border,
    borderRadius: 14,
  },
  repeatEveryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  repeatEveryLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: Palette.text,
  },
  repeatNumberInput: {
    backgroundColor: Palette.surface,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: Palette.text,
    minWidth: 64,
    textAlign: 'center',
  },
  periodToggle: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: Palette.toggleTrack,
    borderRadius: 999,
    padding: 4,
  },
  periodBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 999,
  },
  periodBtnActive: {
    backgroundColor: Palette.cardBackground,
    shadowColor: Palette.shadow,
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  periodText: {
    fontSize: 14,
    fontWeight: '600',
    color: Palette.textSubtle,
  },
  periodTextActive: {
    color: Palette.text,
  },
  endModeToggle: {
    flexDirection: 'row',
    backgroundColor: Palette.toggleTrack,
    borderRadius: 999,
    padding: 4,
  },
  endModeBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 999,
  },
  endModeBtnActive: {
    backgroundColor: Palette.cardBackground,
    shadowColor: Palette.shadow,
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  endModeText: {
    fontSize: 14,
    fontWeight: '600',
    color: Palette.textSubtle,
  },
  endModeTextActive: {
    color: Palette.text,
  },
  repeatSummary: {
    fontSize: 13,
    color: Palette.iconMuted,
    paddingHorizontal: 4,
  },
  kbAccessory: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    backgroundColor: Palette.toggleTrack,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.border,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  kbAccessoryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  kbAccessoryText: {
    fontSize: 16,
    color: Palette.brand,
    fontWeight: '600',
  },
});
