import { StyleSheet } from 'react-native';

import { Palette } from '@/constants/colors';

export const goalEditorStyles = StyleSheet.create({
  modalRoot: {
    flex: 1,
  },
  backdrop: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  sheet: {
    backgroundColor: Palette.cardBackground,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
    gap: 12,
    maxHeight: '92%',
  },
  dragHandleArea: {
    paddingTop: 4,
  },
  grabber: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: Palette.sheetHandle,
    marginBottom: 8,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.border,
  },
  headerLeft: {
    fontSize: 16,
    color: Palette.text,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: Palette.text,
  },
  headerRight: {
    width: 50,
  },
  body: {
    gap: 14,
    paddingTop: 6,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  editColorBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Palette.iconMuted,
    borderStyle: 'dashed',
    backgroundColor: Palette.cardBackground,
  },
  catDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  editColorBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: Palette.cardBackground,
    borderRadius: 7,
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Palette.iconMuted,
  },
  nameInput: {
    flex: 1,
    fontSize: 17,
    fontWeight: '600',
    color: Palette.text,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: Palette.surface,
    borderRadius: 12,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: Palette.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  amountWrap: {
    alignItems: 'center',
    paddingVertical: 6,
    backgroundColor: Palette.surface,
    borderRadius: 12,
  },
  amount: {
    fontSize: 36,
    fontWeight: '700',
    color: Palette.text,
    letterSpacing: -1,
  },
  amountMuted: {
    color: Palette.amountPlaceholder,
  },
  hiddenInput: {
    position: 'absolute',
    opacity: 0,
    height: 1,
    width: 1,
  },
  modeToggle: {
    flexDirection: 'row',
    backgroundColor: Palette.toggleTrack,
    borderRadius: 999,
    padding: 3,
  },
  modeBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 999,
  },
  modeBtnActive: {
    backgroundColor: Palette.cardBackground,
    shadowColor: Palette.shadow,
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  modeText: {
    fontSize: 13,
    fontWeight: '600',
    color: Palette.textSubtle,
  },
  modeTextActive: {
    color: Palette.text,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  numberInput: {
    flex: 1,
    fontSize: 16,
    color: Palette.text,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: Palette.surface,
    borderRadius: 12,
  },
  derivedCard: {
    backgroundColor: Palette.surface,
    borderRadius: 12,
    padding: 12,
    gap: 4,
  },
  derivedTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: Palette.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  derivedValue: {
    fontSize: 18,
    fontWeight: '700',
    color: Palette.text,
  },
  saveBtn: {
    backgroundColor: Palette.brand,
    paddingVertical: 14,
    borderRadius: 999,
    alignItems: 'center',
    marginTop: 6,
  },
  saveText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  saveDisabled: {
    backgroundColor: Palette.submitDisabled,
  },
  kbAccessory: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    backgroundColor: Palette.toggleTrack,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.border,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  kbAccessoryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  kbAccessoryText: {
    fontSize: 16,
    color: Palette.brand,
    fontWeight: '600',
  },
});
